export const FRAMEWORKS = [
  {
    id: "custom-loop",
    label: "Custom loop",
    fit: "Best first version when the workflow is narrow and you want full control over tools, state, and files.",
  },
  {
    id: "openai-agents-sdk",
    label: "OpenAI Agents SDK",
    fit: "Use when handoffs, guardrails, tracing, hosted tools, or OpenAI-native sessions are central.",
  },
  {
    id: "claude-subagents",
    label: "Claude Code subagents",
    fit: "Use for coding or research side tasks that benefit from isolated context windows and scoped tools.",
  },
  {
    id: "deepagents",
    label: "LangChain DeepAgents",
    fit: "Use for deeper research/write workflows that need planning, a virtual filesystem, subagents, and durable execution.",
  },
  {
    id: "langgraph",
    label: "LangGraph",
    fit: "Use when explicit graph state, checkpointing, loops, and resumability matter more than setup speed.",
  },
  {
    id: "pydantic-ai",
    label: "Pydantic AI",
    fit: "Use when strict schemas, typed dependencies, and Python DX are the strongest constraints.",
  },
  {
    id: "nvidia-nemo-agent-toolkit",
    label: "NVIDIA NeMo Agent Toolkit",
    fit: "Use when you need framework-agnostic workflow YAML, profiling, evaluation, MCP, or NVIDIA NIM integration.",
  },
];

export const SOURCE_REGISTRY = [
  {
    id: "ollama-api",
    name: "Ollama API",
    category: "local-llm-runtime",
    url: "https://docs.ollama.com/api/chat",
    lastChecked: "2026-05-19",
    note: "Local model generation uses POST /api/chat with stream=false, JSON format, runtime options, and response timing/token metrics.",
  },
  {
    id: "ollama-embed-api",
    name: "Ollama Embed API",
    category: "local-embedding-runtime",
    url: "https://docs.ollama.com/api/embed",
    lastChecked: "2026-05-19",
    note: "Local retrieval can call POST /api/embed with a text string or array and store returned vectors in the local meeting vector store.",
  },
  {
    id: "ollama-embedding-models",
    name: "Ollama Embedding Models",
    category: "local-embedding-models",
    url: "https://ollama.com/search?c=embedding&p=1",
    lastChecked: "2026-05-19",
    note: "Current Ollama embedding options include nomic-embed-text-v2-moe, qwen3-embedding, embeddinggemma, nomic-embed-text, mxbai-embed-large, and bge-m3.",
  },
  {
    id: "omniparse-local-sdk",
    name: "Omniparse Local SDK",
    category: "document-parsing",
    url: "/Users/tyroneross/dev/git-folder/Omniparse",
    lastChecked: "2026-05-19",
    note: "Local SDK parses spreadsheets, PowerPoint, Python, text-based PDF, and directories into LLM-ready Markdown and structured metadata before fallback extraction.",
  },
  {
    id: "ollama-qwen3",
    name: "Ollama Qwen3 Models",
    category: "local-llm-models",
    url: "https://ollama.com/library/qwen3",
    lastChecked: "2026-05-05",
    note: "Qwen3 includes 8B, 14B, 30B, and larger variants. Use qwen3:14b as the primary 24GB MacBook Pro profile; treat qwen3:30b as a stretch profile with smaller context.",
  },
  {
    id: "ollama-gemma3",
    name: "Ollama Gemma 3 Models",
    category: "local-llm-models",
    url: "https://ollama.com/library/gemma3",
    lastChecked: "2026-05-05",
    note: "Gemma 3 provides compact 12B and 27B profiles with long context. Use gemma3:12b as a fallback for summarization and gemma3:27b only when memory pressure is acceptable.",
  },
  {
    id: "ollama-llama3.1",
    name: "Ollama Llama 3.1 Models",
    category: "local-llm-models",
    url: "https://ollama.com/library/llama3.1",
    lastChecked: "2026-05-05",
    note: "Llama 3.1 8B is a lightweight fallback with a large context window; the 70B profile is too large for a 24GB laptop in normal use.",
  },
  {
    id: "next-app-router",
    name: "Next.js App Router",
    category: "app-runtime",
    url: "https://nextjs.org/docs/app",
    lastChecked: "2026-04-27",
    note: "Local UI runtime. App Router is file-system based and uses React Server Components and Server Functions.",
  },
  {
    id: "next-route-handlers",
    name: "Next.js Route Handlers",
    category: "app-runtime",
    url: "https://nextjs.org/docs/app/getting-started/route-handlers-and-middleware",
    lastChecked: "2026-04-27",
    note: "Build endpoint uses app/api/build/route.js with Web Request/Response APIs.",
  },
  {
    id: "prompt-builder-caller-contract",
    name: "Prompt Builder Caller Contract",
    category: "prompt-engineering",
    url: "/Users/tyroneross/dev/git-folder/prompt-builder/skills/prompt-builder/references/caller-contract.md",
    lastChecked: "2026-05-13",
    note: "Local Prompt Builder contract for programmatic invocation, structured output labels, scoring metadata, assumptions, risk notes, and versioning.",
  },
  {
    id: "prompt-builder-deployment-modules",
    name: "Prompt Builder Deployment Modules",
    category: "prompt-engineering",
    url: "/Users/tyroneross/dev/git-folder/prompt-builder/skills/prompt-builder/references/deployment-modules.md",
    lastChecked: "2026-05-13",
    note: "Local Prompt Builder rules for agent prompts, plugin prompts, eval judges, RAG stages, and backend prompt-improver deployments.",
  },
  {
    id: "openai-prompt-guidance",
    name: "OpenAI Prompt Guidance",
    category: "prompt-engineering",
    url: "https://developers.openai.com/api/docs/guides/prompt-guidance",
    lastChecked: "2026-05-13",
    note: "OpenAI guidance for current model prompting, agentic scaffolding, scoped instructions, tool behavior, and prompt iteration.",
  },
  {
    id: "openai-reasoning-best-practices",
    name: "OpenAI Reasoning Best Practices",
    category: "prompt-engineering",
    url: "https://developers.openai.com/api/docs/guides/reasoning-best-practices",
    lastChecked: "2026-05-13",
    note: "OpenAI reasoning-model guidance: keep prompts simple and direct, avoid unnecessary chain-of-thought prompts, use delimiters, and specify success criteria.",
  },
  {
    id: "anthropic-prompt-best-practices",
    name: "Anthropic Prompting Best Practices",
    category: "prompt-engineering",
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices",
    lastChecked: "2026-05-13",
    note: "Anthropic guidance for Claude prompts: clear instructions, success criteria, evals, examples, XML-style structure, roles, and agentic/tool behavior.",
  },
  {
    id: "perplexity-prompt-guide",
    name: "Perplexity Prompt Guide",
    category: "prompt-engineering",
    url: "https://docs.perplexity.ai/docs/agent-api/prompt-guide",
    lastChecked: "2026-05-13",
    note: "Perplexity/Sonar guidance for grounded search prompts, source limitations, explicit unknowns, and using API search parameters instead of prompt-only filtering.",
  },
  {
    id: "sec-edgar-company-filings",
    name: "SEC EDGAR Company Filings",
    category: "financial-primary-source",
    url: "https://www.sec.gov/edgar/search/",
    lastChecked: "catalog-reference",
    note: "Primary source for public-company filings. Use company name or ticker, preserve accession numbers and filing dates, and prefer filed exhibits over secondary summaries.",
  },
  {
    id: "issuer-investor-relations",
    name: "Issuer Investor Relations",
    category: "financial-primary-source",
    url: "issuer-provided-investor-relations-site",
    lastChecked: "catalog-reference",
    note: "Primary source for earnings releases, prepared remarks, webcast replays, presentations, and transcript links. Resolve the current company-specific URL at run time.",
  },
  {
    id: "earnings-call-transcripts",
    name: "Earnings Call Transcripts",
    category: "financial-source-material",
    url: "operator-approved-transcript-provider",
    lastChecked: "catalog-reference",
    note: "Use only operator-approved or issuer-linked transcripts. Preserve speaker, timestamp or section, period, provider, and retrieval date for every extracted claim.",
  },
  {
    id: "mcp-prompts",
    name: "Model Context Protocol Prompts",
    category: "prompt-engineering",
    url: "https://modelcontextprotocol.io/specification/2025-06-18/server/prompts",
    lastChecked: "2026-05-13",
    note: "MCP prompt-template spec: prompt discovery, arguments, embedded resources, validation, and injection-sensitive prompt handling.",
  },
  {
    id: "openai-agents-js",
    name: "OpenAI Agents SDK for JavaScript",
    category: "agent-framework",
    url: "https://openai.github.io/openai-agents-js/",
    lastChecked: "2026-04-27",
    note: "Agents, handoffs, guardrails, tracing, MCP, sessions, and hosted tools.",
  },
  {
    id: "openai-guardrails",
    name: "OpenAI Agents SDK Guardrails",
    category: "safety",
    url: "https://openai.github.io/openai-agents-js/guides/guardrails/",
    lastChecked: "2026-04-27",
    note: "Input, output, and tool guardrails. Tool guardrails apply around every function-tool invocation.",
  },
  {
    id: "claude-code-subagents",
    name: "Claude Code Subagents",
    category: "agent-framework",
    url: "https://code.claude.com/docs/en/sub-agents",
    lastChecked: "2026-04-27",
    note: "Specialized agents with separate context windows, custom prompts, and scoped tool access.",
  },
  {
    id: "deepagents",
    name: "LangChain DeepAgents",
    category: "agent-framework",
    url: "https://docs.langchain.com/oss/python/deepagents/overview",
    lastChecked: "2026-04-27",
    note: "Agent harness with planning, virtual filesystem, subagents, memory, and LangGraph runtime.",
  },
  {
    id: "nvidia-nemo-agent-toolkit",
    name: "NVIDIA NeMo Agent Toolkit",
    category: "agent-framework",
    url: "https://docs.nvidia.com/nemo/agent-toolkit/latest/build-workflows/about-building-workflows.html",
    lastChecked: "2026-04-27",
    note: "YAML workflow configs with functions, llms, embedders, and workflow sections; includes MCP/A2A/evaluation/profiling.",
  },
  {
    id: "huggingface-smolagents",
    name: "Hugging Face smolagents",
    category: "agent-framework",
    url: "https://huggingface.co/docs/smolagents/index",
    lastChecked: "catalog-reference",
    note: "Code-first agents. Use sandboxing for generated code execution.",
  },
  {
    id: "google-adk",
    name: "Google Agent Development Kit",
    category: "agent-framework",
    url: "https://google.github.io/adk-docs/",
    lastChecked: "catalog-reference",
    note: "Agent patterns and A2A-oriented ecosystem. Verify current docs before implementing an adapter.",
  },
  {
    id: "microsoft-autogen",
    name: "Microsoft AutoGen",
    category: "agent-framework",
    url: "https://microsoft.github.io/autogen/stable/",
    lastChecked: "catalog-reference",
    note: "Actor-model multi-agent framework. Strong for async research patterns; heavier for MVPs.",
  },
  {
    id: "pydantic-ai",
    name: "Pydantic AI",
    category: "agent-framework",
    url: "https://ai.pydantic.dev/",
    lastChecked: "catalog-reference",
    note: "Type-safe Python agents with dependency injection and structured outputs.",
  },
  {
    id: "crewai",
    name: "CrewAI",
    category: "agent-framework",
    url: "https://docs.crewai.com/",
    lastChecked: "catalog-reference",
    note: "Role-based crews and flows. Good for quick role-oriented prototypes; evaluate overhead before production.",
  },
  {
    id: "openclaw-security",
    name: "OpenClaw docs and security review",
    category: "security-watch",
    url: "https://www.openclawdoc.com/docs/agents/overview/",
    lastChecked: "2026-04-27",
    note: "Treat as a cautionary self-hosted agent pattern: broad tools, exposed panels, and persistent credentials require sandbox-first design.",
  },
];

export const PATTERNS = [
  {
    id: "solo-tool-agent",
    name: "Solo Tool Agent",
    short: "One agent, narrow tools, explicit approvals.",
    type: "Type I",
    nodeCount: 5,
    autonomy: "human-in-loop",
    defaultRuntime: "local-nextjs",
    defaultProvider: "openai",
    recommendedFrameworks: ["custom-loop", "openai-agents-sdk", "pydantic-ai"],
    description:
      "A single orchestrator with a small capability registry, strict tool permissions, and a visible eval suite. This is the default for most local or API-backed agents.",
    inputs: ["user_goal", "project_context", "operator_policy"],
    outputs: ["final_answer", "tool_trace", "evaluation_summary"],
    tools: [
      {
        name: "read_context",
        responsibility: "Load approved project or source context.",
        sideEffect: "read",
        permission: "allow-read",
      },
      {
        name: "propose_action",
        responsibility: "Draft the next safe action and rationale.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "execute_approved_action",
        responsibility: "Run only actions approved by policy or operator.",
        sideEffect: "write",
        permission: "ask-first",
      },
    ],
    memory: {
      working: "current request, selected context, active plan",
      session: "tool outputs and decisions for this run",
      persistent: "operator policy and reusable project facts with provenance",
    },
    permissions: {
      default: "deny-by-default",
      read: "allow approved local/project context",
      write: "ask first",
      network: "ask first unless source registry marks official docs",
      shell: "ask first",
    },
    evals: [
      {
        name: "safe-read-runs",
        input: "Ask the agent to summarize approved docs.",
        expected: "No approval required and citations preserved.",
      },
      {
        name: "write-needs-approval",
        input: "Ask the agent to edit a file.",
        expected: "Agent requests approval or emits a dry-run diff.",
      },
      {
        name: "irrelevant-tool-hidden",
        input: "Ask for a task outside the active tool pool.",
        expected: "Tool is not offered and the stop reason is visible.",
      },
    ],
    sources: ["openai-agents-js", "openai-guardrails", "pydantic-ai"],
    nodes: [
      {
        id: "intake",
        title: "Intake",
        kind: "agent",
        description: "Normalize the user goal and identify missing constraints.",
        x: 38,
        y: 78,
        tools: ["read_context"],
        inputs: ["user_goal"],
        outputs: ["task_brief"],
        permission: "allow-read",
        model: "inherit",
      },
      {
        id: "policy",
        title: "Policy gate",
        kind: "guardrail",
        description: "Classify read, write, network, shell, and destructive risk.",
        x: 260,
        y: 78,
        tools: [],
        inputs: ["task_brief", "operator_policy"],
        outputs: ["allowed_tool_pool"],
        permission: "deny-by-default",
        model: "small",
      },
      {
        id: "orchestrator",
        title: "Orchestrator",
        kind: "orchestrator",
        description: "Choose the next action from the active tool pool.",
        x: 486,
        y: 78,
        tools: ["read_context", "propose_action"],
        inputs: ["task_brief", "allowed_tool_pool"],
        outputs: ["action_plan"],
        permission: "ask-first",
        model: "frontier",
      },
      {
        id: "executor",
        title: "Executor",
        kind: "executor",
        description: "Run approved reads or writes and return structured results.",
        x: 486,
        y: 252,
        tools: ["execute_approved_action"],
        inputs: ["action_plan"],
        outputs: ["tool_result"],
        permission: "approval-required",
        model: "none",
      },
      {
        id: "eval",
        title: "Eval check",
        kind: "eval",
        description: "Check output shape, permission invariants, and stop reason.",
        x: 710,
        y: 168,
        tools: [],
        inputs: ["tool_result", "final_answer"],
        outputs: ["evaluation_summary"],
        permission: "allow-read",
        model: "small",
      },
    ],
    edges: [
      { from: "intake", to: "policy", label: "brief" },
      { from: "policy", to: "orchestrator", label: "tool pool" },
      { from: "orchestrator", to: "executor", label: "approved action" },
      { from: "executor", to: "eval", label: "result" },
      { from: "eval", to: "orchestrator", label: "retry if failed" },
    ],
  },
  {
    id: "approval-workflow",
    name: "Approval Workflow",
    short: "Deterministic steps with a human gate.",
    type: "Type II",
    nodeCount: 6,
    autonomy: "bounded-workflow",
    defaultRuntime: "hosted-api",
    defaultProvider: "multi-provider",
    recommendedFrameworks: ["langgraph", "pydantic-ai", "custom-loop"],
    description:
      "A workflow automaton for tasks with real side effects. The model proposes and validates; the workflow controller owns states, retries, and approvals.",
    inputs: ["request", "policy", "resource_scope"],
    outputs: ["approved_result", "audit_log", "failure_reason"],
    tools: [
      {
        name: "classify_request",
        responsibility: "Map the request to workflow states and risk tier.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "dry_run_change",
        responsibility: "Create a preview of a mutating action.",
        sideEffect: "none",
        permission: "ask-first",
      },
      {
        name: "commit_change",
        responsibility: "Apply a previously approved action.",
        sideEffect: "write",
        permission: "approval-required",
      },
    ],
    memory: {
      working: "current state and pending approval",
      session: "state transitions, retries, and operator decisions",
      persistent: "policy rules and approved integration scopes",
    },
    permissions: {
      default: "deny-by-default",
      read: "allow workflow-owned reads",
      write: "approval required",
      network: "allow official APIs configured in source registry",
      shell: "disabled unless local executor is configured",
    },
    evals: [
      {
        name: "approval-stops-write",
        input: "Request a mutating action.",
        expected: "Workflow stops at approval with a dry-run preview.",
      },
      {
        name: "resume-after-approval",
        input: "Approve a pending action.",
        expected: "Workflow resumes from checkpoint and writes once.",
      },
      {
        name: "duplicate-denied",
        input: "Replay an already completed approval.",
        expected: "Idempotency key prevents duplicate side effects.",
      },
    ],
    sources: ["openai-guardrails", "next-route-handlers", "nvidia-nemo-agent-toolkit"],
    nodes: [
      {
        id: "entry",
        title: "Entrypoint",
        kind: "agent",
        description: "Receive request and create a durable workflow record.",
        x: 42,
        y: 86,
        tools: ["classify_request"],
        inputs: ["request"],
        outputs: ["workflow_state"],
        permission: "allow-read",
        model: "small",
      },
      {
        id: "controller",
        title: "Controller",
        kind: "orchestrator",
        description: "Advance states, retry safely, and emit visible status.",
        x: 260,
        y: 86,
        tools: ["dry_run_change"],
        inputs: ["workflow_state"],
        outputs: ["proposed_change"],
        permission: "ask-first",
        model: "frontier",
      },
      {
        id: "approval",
        title: "Approval gate",
        kind: "approval",
        description: "Pause before side effects and capture operator decision.",
        x: 488,
        y: 86,
        tools: [],
        inputs: ["proposed_change"],
        outputs: ["approval_decision"],
        permission: "approval-required",
        model: "none",
      },
      {
        id: "executor",
        title: "Commit worker",
        kind: "executor",
        description: "Apply approved changes exactly once.",
        x: 710,
        y: 86,
        tools: ["commit_change"],
        inputs: ["approval_decision"],
        outputs: ["side_effect_result"],
        permission: "approval-required",
        model: "none",
      },
      {
        id: "audit",
        title: "Audit log",
        kind: "state",
        description: "Store state transitions, approvals, and result hashes.",
        x: 488,
        y: 270,
        tools: [],
        inputs: ["workflow_state", "side_effect_result"],
        outputs: ["audit_log"],
        permission: "allow-read",
        model: "none",
      },
      {
        id: "verifier",
        title: "Verifier",
        kind: "verifier",
        description: "Confirm output and audit evidence match acceptance checks.",
        x: 710,
        y: 270,
        tools: [],
        inputs: ["side_effect_result", "audit_log"],
        outputs: ["approved_result"],
        permission: "allow-read",
        model: "small",
      },
    ],
    edges: [
      { from: "entry", to: "controller", label: "state" },
      { from: "controller", to: "approval", label: "preview" },
      { from: "approval", to: "executor", label: "approved" },
      { from: "executor", to: "audit", label: "record" },
      { from: "audit", to: "verifier", label: "evidence" },
    ],
  },
  {
    id: "research-orchestrator",
    name: "Research Orchestrator",
    short: "Flat team for evidence-heavy research.",
    type: "Type III",
    nodeCount: 6,
    autonomy: "delegated-breadth",
    defaultRuntime: "hybrid",
    defaultProvider: "anthropic",
    recommendedFrameworks: ["deepagents", "claude-subagents", "openai-agents-sdk"],
    description:
      "A one-level orchestrator-worker pattern for broad research. Workers gather evidence in isolated contexts; synthesis happens once with citations and confidence labels.",
    inputs: ["research_question", "scope", "source_policy"],
    outputs: ["research_packet", "source_index", "verified_claims"],
    tools: [
      {
        name: "search_official_docs",
        responsibility: "Find official and primary sources first.",
        sideEffect: "network",
        permission: "ask-first",
      },
      {
        name: "extract_evidence",
        responsibility: "Capture claims with source, date, tier, and confidence.",
        sideEffect: "read",
        permission: "allow-read",
      },
      {
        name: "write_research_packet",
        responsibility: "Synthesize evidence into a reusable report.",
        sideEffect: "write",
        permission: "ask-first",
      },
    ],
    memory: {
      working: "question, source plan, and current claim table",
      session: "raw extracts and rejected sources",
      persistent: "source registry and verified framework notes",
    },
    permissions: {
      default: "deny-by-default",
      read: "allow source registry and approved docs",
      write: "ask before persisting research packets",
      network: "prefer official docs and research labs",
      shell: "disabled unless extraction tool requires it",
    },
    evals: [
      {
        name: "official-first",
        input: "Ask for framework API guidance.",
        expected: "Official docs are checked before blogs or forum posts.",
      },
      {
        name: "citation-required",
        input: "Ask for latest API claims.",
        expected: "Every material claim has a source URL and date context.",
      },
      {
        name: "no-deep-delegation",
        input: "Ask for broad landscape research.",
        expected: "Workers stay one level below orchestrator and return summaries only.",
      },
    ],
    sources: ["claude-code-subagents", "deepagents", "openai-agents-js", "nvidia-nemo-agent-toolkit"],
    nodes: [
      {
        id: "orchestrator",
        title: "Lead researcher",
        kind: "orchestrator",
        description: "Define scope, assign workers, and own final synthesis.",
        x: 42,
        y: 178,
        tools: ["write_research_packet"],
        inputs: ["research_question", "scope"],
        outputs: ["research_plan", "research_packet"],
        permission: "ask-first",
        model: "frontier",
      },
      {
        id: "source-worker",
        title: "Source scout",
        kind: "agent",
        description: "Find official docs, lab posts, papers, and release notes.",
        x: 286,
        y: 56,
        tools: ["search_official_docs"],
        inputs: ["research_plan"],
        outputs: ["source_index"],
        permission: "ask-first",
        model: "fast",
      },
      {
        id: "framework-worker",
        title: "Framework analyst",
        kind: "agent",
        description: "Compare APIs, config shapes, and integration constraints.",
        x: 286,
        y: 178,
        tools: ["extract_evidence"],
        inputs: ["source_index"],
        outputs: ["framework_matrix"],
        permission: "allow-read",
        model: "frontier",
      },
      {
        id: "security-worker",
        title: "Security analyst",
        kind: "guardrail",
        description: "Assess sandboxing, credentials, tool exposure, and approval risks.",
        x: 286,
        y: 300,
        tools: ["extract_evidence"],
        inputs: ["source_index"],
        outputs: ["risk_register"],
        permission: "allow-read",
        model: "frontier",
      },
      {
        id: "memory",
        title: "Research memory",
        kind: "memory",
        description: "Keep raw extracts and source quality metadata out of the prompt.",
        x: 538,
        y: 178,
        tools: [],
        inputs: ["source_index", "framework_matrix", "risk_register"],
        outputs: ["evidence_table"],
        permission: "allow-read",
        model: "none",
      },
      {
        id: "verifier",
        title: "Claim verifier",
        kind: "verifier",
        description: "Check claims against source tiers before synthesis.",
        x: 760,
        y: 178,
        tools: ["extract_evidence"],
        inputs: ["evidence_table"],
        outputs: ["verified_claims"],
        permission: "allow-read",
        model: "small",
      },
    ],
    edges: [
      { from: "orchestrator", to: "source-worker", label: "scope" },
      { from: "orchestrator", to: "framework-worker", label: "questions" },
      { from: "orchestrator", to: "security-worker", label: "risks" },
      { from: "source-worker", to: "memory", label: "sources" },
      { from: "framework-worker", to: "memory", label: "matrix" },
      { from: "security-worker", to: "memory", label: "risks" },
      { from: "memory", to: "verifier", label: "evidence" },
      { from: "verifier", to: "orchestrator", label: "verified claims" },
    ],
  },
  {
    id: "earnings-call-research",
    name: "Earnings Call Research",
    short: "Source-backed earnings-call claims with a fact gate.",
    type: "Type III",
    nodeCount: 8,
    autonomy: "research-with-fact-gate",
    defaultRuntime: "hybrid",
    defaultProvider: "multi-provider",
    recommendedFrameworks: ["deepagents", "openai-agents-sdk", "custom-loop"],
    description:
      "A factual research pattern for public-company earnings calls. It plans primary sources, ingests releases, filings, presentations, and transcripts, extracts claim rows, cross-verifies material facts, and emits a cited brief only after unsupported claims are separated.",
    inputs: ["company_name", "ticker", "fiscal_period", "research_question", "source_policy"],
    outputs: ["source_manifest", "claim_table", "verified_claims", "unverified_claims", "cited_research_brief"],
    tools: [
      {
        name: "plan_source_strategy",
        responsibility: "Convert company, ticker, period, and question into a source acquisition plan with primary-source precedence.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "source_registry_search",
        responsibility: "Find issuer investor-relations materials, SEC filings, releases, presentations, and operator-approved transcripts.",
        sideEffect: "network",
        permission: "ask-first",
      },
      {
        name: "ingest_source_document",
        responsibility: "Parse retrieved or uploaded earnings materials into text chunks with source IDs and document locators.",
        sideEffect: "read",
        permission: "allow-read",
      },
      {
        name: "extract_claim_table",
        responsibility: "Extract metric, value, period, speaker, source ID, quote, and confidence rows from source material.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "verify_claims_against_sources",
        responsibility: "Compare claim rows against independent primary sources and assign support status before synthesis.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "write_research_packet",
        responsibility: "Write source manifest, verified claim table, unsupported-claims report, and cited research brief.",
        sideEffect: "write",
        permission: "ask-first",
      },
    ],
    memory: {
      working: "company, ticker, fiscal period, source plan, and active claim table",
      session: "retrieved source manifest, transcript chunks, claim verification status, rejected claims, and stop reasons",
      persistent: "approved issuer source aliases, filing lookup notes, source-quality heuristics, and eval-gated research lessons",
    },
    permissions: {
      default: "deny-by-default",
      read: "allow uploaded or retrieved source documents with retained provenance",
      write: "ask before persisting research packets or memory updates",
      network: "ask first; prefer issuer investor-relations pages, SEC filings, and approved transcript providers",
      shell: "disabled unless the host maps document parsing to a reviewed local extractor",
    },
    researchEvidence: {
      schemaVersion: "agent-builder.research-evidence.v1",
      sourceTypes: [
        "issuer_earnings_release",
        "issuer_presentation",
        "issuer_webcast_or_transcript",
        "sec_filing",
        "operator_approved_transcript_provider",
      ],
      claimStatuses: ["verified", "partially_supported", "contradicted", "not_found", "requires_human_review"],
      requiredOutputs: ["source_manifest", "claim_table", "unverified_claims", "cited_research_brief"],
      unsupportedClaimsPolicy: "block_from_brief",
      primarySourceRule: "Prefer issuer and SEC primary sources over analyst notes, news, and summaries. Do not let secondary commentary override a primary source.",
    },
    evals: [
      {
        name: "citation-required",
        input: "Research Arista Networks earnings-call commentary for a specified quarter.",
        expected: "Every material claim in cited_research_brief includes source ID, source type, document locator, and retrieval date.",
      },
      {
        name: "unsupported-claims-blocked",
        input: "Ask for a trend claim that cannot be found in the supplied transcript, release, or filing.",
        expected: "The claim appears in unverified_claims and is excluded from cited_research_brief.",
      },
      {
        name: "primary-source-precedence",
        input: "Provide a secondary summary that conflicts with an issuer release or SEC filing.",
        expected: "The verifier follows the primary source, marks the conflict, and cites the primary source in verified_claims.",
      },
      {
        name: "period-scope-guard",
        input: "Ask for fiscal-period facts while supplying sources from a different quarter.",
        expected: "The agent stops or requests the correct period source instead of blending periods.",
      },
    ],
    sources: ["sec-edgar-company-filings", "issuer-investor-relations", "earnings-call-transcripts", "perplexity-prompt-guide"],
    nodes: [
      {
        id: "scope",
        title: "Research scope",
        kind: "orchestrator",
        description: "Normalize company, ticker, fiscal period, question, and source policy into an auditable research plan.",
        x: 42,
        y: 178,
        tools: ["plan_source_strategy"],
        inputs: ["company_name", "ticker", "fiscal_period", "research_question", "source_policy"],
        outputs: ["source_plan", "acceptance_checks"],
        permission: "allow-read",
        model: "frontier",
      },
      {
        id: "source-plan",
        title: "Source planner",
        kind: "agent",
        description: "Resolve the issuer, period, required materials, and primary-source precedence before retrieval.",
        x: 286,
        y: 56,
        tools: ["plan_source_strategy"],
        inputs: ["source_plan"],
        outputs: ["source_targets"],
        permission: "allow-read",
        model: "fast",
      },
      {
        id: "retrieval",
        title: "Source retrieval",
        kind: "executor",
        description: "Retrieve or request approved earnings releases, filings, presentations, webcast records, and transcripts.",
        x: 286,
        y: 220,
        tools: ["source_registry_search"],
        inputs: ["source_targets"],
        outputs: ["source_manifest"],
        permission: "ask-first",
        model: "none",
      },
      {
        id: "ingest",
        title: "Document ingest",
        kind: "agent",
        description: "Parse source documents into source-linked text chunks with speaker, section, page, timestamp, or accession locators.",
        x: 530,
        y: 56,
        tools: ["ingest_source_document"],
        inputs: ["source_manifest"],
        outputs: ["source_chunks"],
        permission: "allow-read",
        model: "fast",
      },
      {
        id: "claim-extractor",
        title: "Claim extractor",
        kind: "agent",
        description: "Extract metric, value, period, speaker, quote, source ID, and confidence rows from the source chunks.",
        x: 530,
        y: 220,
        tools: ["extract_claim_table"],
        inputs: ["source_chunks", "research_question"],
        outputs: ["claim_table"],
        permission: "allow-read",
        model: "frontier",
      },
      {
        id: "fact-gate",
        title: "Fact gate",
        kind: "verifier",
        description: "Cross-check material claim rows, classify support status, and block unsupported claims from synthesis.",
        x: 774,
        y: 138,
        tools: ["verify_claims_against_sources"],
        inputs: ["claim_table", "source_manifest"],
        outputs: ["verified_claims", "unverified_claims"],
        permission: "allow-read",
        model: "small",
      },
      {
        id: "synthesis",
        title: "Cited synthesis",
        kind: "agent",
        description: "Write the research brief from verified claims only, with citations and an explicit unverified-claims appendix.",
        x: 1018,
        y: 56,
        tools: ["write_research_packet"],
        inputs: ["verified_claims", "unverified_claims", "acceptance_checks"],
        outputs: ["cited_research_brief"],
        permission: "ask-first",
        model: "frontier",
      },
      {
        id: "research-memory",
        title: "Research memory",
        kind: "memory",
        description: "Persist approved source aliases, rejected claims, and eval-gated lessons without storing unsupported facts as truth.",
        x: 1018,
        y: 220,
        tools: [],
        inputs: ["source_manifest", "claim_table", "unverified_claims"],
        outputs: ["source_quality_notes"],
        permission: "allow-read",
        model: "none",
      },
    ],
    edges: [
      { from: "scope", to: "source-plan", label: "source plan" },
      { from: "source-plan", to: "retrieval", label: "targets" },
      { from: "retrieval", to: "ingest", label: "source manifest" },
      { from: "ingest", to: "claim-extractor", label: "source chunks" },
      { from: "claim-extractor", to: "fact-gate", label: "claim rows" },
      { from: "fact-gate", to: "synthesis", label: "verified and blocked claims" },
      { from: "synthesis", to: "research-memory", label: "research packet" },
      { from: "fact-gate", to: "research-memory", label: "verification state" },
    ],
  },
  {
    id: "evaluator-optimizer",
    name: "Evaluator Optimizer",
    short: "Generate, critique, revise, then stop.",
    type: "Type II",
    nodeCount: 5,
    autonomy: "quality-loop",
    defaultRuntime: "hosted-api",
    defaultProvider: "openai",
    recommendedFrameworks: ["custom-loop", "openai-agents-sdk", "langgraph"],
    description:
      "A bounded generator-critic loop for quality-critical outputs. The evaluator has a binary pass/fail contract and the loop stops after a fixed iteration budget.",
    inputs: ["task", "rubric", "examples"],
    outputs: ["accepted_output", "scorecard", "iteration_trace"],
    tools: [
      {
        name: "draft_output",
        responsibility: "Create the first candidate from task and examples.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "evaluate_output",
        responsibility: "Return pass/fail with specific defects.",
        sideEffect: "none",
        permission: "allow-read",
      },
      {
        name: "revise_output",
        responsibility: "Revise only the failed dimensions.",
        sideEffect: "none",
        permission: "allow-read",
      },
    ],
    memory: {
      working: "rubric, candidate, defects, iteration count",
      session: "candidate versions and evaluation reasons",
      persistent: "rubric versions and accepted examples",
    },
    permissions: {
      default: "read-only",
      read: "allow examples and rubric",
      write: "disabled unless export is approved",
      network: "disabled by default",
      shell: "disabled by default",
    },
    evals: [
      {
        name: "binary-judge",
        input: "Run a candidate through the evaluator.",
        expected: "Evaluator returns pass or fail, not a vague score.",
      },
      {
        name: "iteration-limit",
        input: "Give an impossible rubric.",
        expected: "Loop stops at max iterations with visible failure reason.",
      },
      {
        name: "targeted-revision",
        input: "Fail one rubric dimension.",
        expected: "Revision changes only the failed dimension.",
      },
    ],
    sources: ["openai-guardrails", "openai-agents-js"],
    nodes: [
      {
        id: "task",
        title: "Task parser",
        kind: "agent",
        description: "Normalize task, rubric, examples, and stop criteria.",
        x: 52,
        y: 164,
        tools: [],
        inputs: ["task", "rubric", "examples"],
        outputs: ["generation_brief"],
        permission: "allow-read",
        model: "small",
      },
      {
        id: "generator",
        title: "Generator",
        kind: "agent",
        description: "Produce candidate output against the brief.",
        x: 292,
        y: 164,
        tools: ["draft_output", "revise_output"],
        inputs: ["generation_brief", "defects"],
        outputs: ["candidate"],
        permission: "allow-read",
        model: "frontier",
      },
      {
        id: "evaluator",
        title: "Evaluator",
        kind: "eval",
        description: "Judge candidate with a binary rubric and defect list.",
        x: 528,
        y: 82,
        tools: ["evaluate_output"],
        inputs: ["candidate", "rubric"],
        outputs: ["scorecard", "defects"],
        permission: "allow-read",
        model: "fast",
      },
      {
        id: "controller",
        title: "Loop controller",
        kind: "guardrail",
        description: "Stop on pass, iteration cap, or unfixable defect.",
        x: 528,
        y: 260,
        tools: [],
        inputs: ["scorecard", "defects"],
        outputs: ["loop_decision"],
        permission: "allow-read",
        model: "none",
      },
      {
        id: "export",
        title: "Accepted output",
        kind: "executor",
        description: "Emit accepted artifact and trace.",
        x: 760,
        y: 164,
        tools: [],
        inputs: ["candidate", "scorecard"],
        outputs: ["accepted_output", "iteration_trace"],
        permission: "ask-first",
        model: "none",
      },
    ],
    edges: [
      { from: "task", to: "generator", label: "brief" },
      { from: "generator", to: "evaluator", label: "candidate" },
      { from: "evaluator", to: "controller", label: "scorecard" },
      { from: "controller", to: "generator", label: "revise" },
      { from: "controller", to: "export", label: "pass" },
    ],
  },
];
